export { default as Hero } from "./Hero.astro"
export { default as About } from "./About.astro"
export { default as Skills } from "./Skills.astro"
export { default as Experiences } from "./Experiences.astro"
export { default as GithubContributions } from "./GithubContributions.astro"
export { default as Projects } from "./Projects.astro"
export { default as Contact } from "./Contact.astro"
export { default as Footer } from "./Footer.astro"
